[project]
name = "projects-api-app"
version = "0.1.0"
description = "Cegeka Tech Project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask-restx>=1.3.0",
    "flask>=3.1.0",
    "pytest>=8.3.4",
]

[dependency-groups]
dev = [
    "isort>=6.0.0",
    "ruff>=0.9.7",
]
